version: "3.4" #for production server(azure VM)
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/templates:/etc/nginx/templates"
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=gogetter.kr
    restart: unless-stopped
    depends_on:
      - authserver
      - springboot
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  authserver:
    container_name: authserver
    image: ${DOCKER_REGISTRY-}authenticationserverapi
    build:
      context: AuthenticationServer.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    expose:
      - 80
  springboot:
    container_name: springboot
    environment:
      - spring_profiles_active=prod
    expose:
      - 8080
    build:
      context: ApplicationServer
      dockerfile: Dockerfile
    depends_on:
      - authserver
