version: "3.4"

services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/templates:/etc/nginx/templates"
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
    restart: unless-stopped
    depends_on:
      - authserver
    #entrypoint: "./wait-for.sh authserver:80 -- /docker-entrypoint.sh nginx -g 'daemon off;'"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  authserver:
    container_name: authserver
    image: ${DOCKER_REGISTRY-}authenticationserverapi
    build:
      context: AuthenticationServer.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings__URL=https://localhost
    expose:
      - 80
    depends_on:
      - mysql
    entrypoint: "./wait-for.sh mysql:3306 -- dotnet AuthenticationServer.API.dll"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  springboot:
    container_name: springboot
    environment:
      - spring_profiles_active=Development
    expose:
      - 8080
    build:
      context: ApplicationServer
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - authserver
    entrypoint: "./wait-for.sh authserver:80 -- java -jar /usr/src/app/app.jar"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PiI4I65otC04Ut
      - MYSQL_DATABASE=gogetters
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=PiI4I65otC04Ut
      - LC_ALL=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    image: "mysql:8.0.29"
    command: >
      bash -c "
      chmod 644 /etc/mysql/my.cnf
      && /entrypoint.sh mysqld
      "
